version: "3"
services:
  ##############
  # Conduit (matrix server) Web EdgeApp
  ##############
  conduit-ws:
    image: ghcr.io/edgebox-iot/apps/conduit:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-conduit-ws'
    restart: unless-stopped
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - conduit-db:/var/lib/matrix-conduit/
    environment:
        VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
        VIRTUAL_PORT: 6167
        CONDUIT_SERVER_NAME: ${CONDUIT_DOMAIN}
        CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
        CONDUIT_DATABASE_BACKEND: rocksdb
        CONDUIT_PORT: 6167
        CONDUIT_MAX_REQUEST_SIZE: 20_000_000 # in bytes, ~20 MB
        CONDUIT_ALLOW_REGISTRATION: '${CONDUIT_ALLOW_REGISTRATION-true}'
        CONDUIT_ALLOW_FEDERATION: '${CONDUIT_ALLOW_FEDERATION-true}'
        CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
        CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
        #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
        #CONDUIT_LOG: warn,rocket=off,_=off,sled=off
        CONDUIT_ADDRESS: 0.0.0.0
        CONDUIT_CONFIG: '' # Ignore this

volumes:
  conduit-db:
