version: "3"
services:
  codeserver-ws:
    image: ghcr.io/edgebox-iot/apps/codeserver:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-codeserver-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      VIRTUAL_PORT: 8080
    volumes:
      - ./appdata/.config/code-server:/home/coder/.config/code-server:rw
      - ./appdata/.local/share/code-server:/home/coder/.local/share/code-server:rw
      - ./appdata/workspace:/home/coder/project:rw