version: "3"
services:
  ##############
  # Focalboard Web EdgeApp
  ##############
  focalboard-ws:
    image: nicoulaj/focalboard
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-focalboard-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
    - ./appdata/ws/apt/focalboard/config.json:/opt/focalboard/config.json
    - ./appdata/ws/var/lib/focalboard:/var/lib/focalboard
    restart: unless-stopped