version: "3"
services:
  ##############
  # Bitwarden EdgeApp
  ##############
  bitwarden-ws:
    image: ghcr.io/edgebox-iot/apps/bitwarden:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-bitwarden-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      SIGNUPS_ALLOWED: '${BITWARDEN_SIGNUPS_ALLOWED}'
      ADMIN_TOKEN: '${BITWARDEN_ADMIN_TOKEN}'
      DOMAIN: http://${LOCAL_URL}
    volumes:
      - ./appdata/config:/data/:rw
    restart: unless-stopped
