version: "3"
services:
  appsmith-ws:
    image: ghcr.io/edgebox-iot/apps/appsmith:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-appsmith-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
    volumes:
      - ./appdata/appsmith-ws/stacks:/appsmith-stacks