version: "3"
services:
  appsmith-ws:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-appsmith-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}