version: "3"
services:
  ##############
  # Writebook EdgeApp
  ##############
  writebook-ws:
    image: ghcr.io/edgebox-iot/apps/writebook:1.0.0
    build:
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-writebook-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      VIRTUAL_PORT: 80
      DISABLE_SSL: "true"
      SECRET_KEY_BASE: '${WRITEBOOK_SECRET_KEY_BASE}'
    volumes:
      - ./appdata/storage:/rails/storage:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
