version: "3"
services:
  ##############
  # OpenWebUI Web EdgeApp
  ##############
  openwebui-ws:
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-openwebui-ws'
    image: ghcr.io/edgebox-iot/apps/openwebui:1.0.0
    build:  
      context: "./"
    user: "0:0"
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      VIRTUAL_PORT: 8080
      TZ: Europe/Germany
      OLLAMA_BASE_URL: ${OPENWEBUI_OLLAMA_BASE_URL}
      OPENAI_API_KEY: ${OPENWEBUI_OPENAI_API_KEY}
    volumes:
      - ./appdata/openwebui-ws:/app/backend/data:rw
    restart: unless-stopped