version: "3"
services:
  ##############
  # n8n EdgeApp
  ##############
  n8n-ws:
    build:
      context: "./bin/n8n-ws/${BUILD_ARCH}"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-n8n-ws'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appdata/ws/data:/home/node/.n8n
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      N8N_HOST: ${MAIN_URL-localhost}
      N8N_PORT: 80
      WEBHOOK_URL: https://${MAIN_URL-localhost}/
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"



