services:
  #################
  # Umami EdgeApp #
  #################
  umami-ws:
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-umami-ws'
    image: ghcr.io/edgebox-iot/apps/umami:1.0.0
    build:  
      context: "./"
    environment:
      VIRTUAL_HOST: ${LOCAL_URL-umami.local}${INTERNET_URL-}
      VIRTUAL_PORT: 3000
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${LISTMONK_SECRET_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      umami-db:
        condition: service_healthy
    restart: unless-stopped

  umami-db:
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-umami-db'
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./appdata/umami-db/:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
