version: "3"
services:
  ##############
  # Filebrowser EdgeApp
  ##############
  filebrowser-ws:
    image: ghcr.io/edgebox-iot/apps/filebrowser:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-filebrowser-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
    volumes:
      - ../..:/srv
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped 