version: "3"
services:
  ##############
  # Uptime Kuma EdgeApp
  ##############
  uptimekuma-ws:
    image: louislam/uptime-kuma:1
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-uptimekuma-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
    volumes:
      - ./appdata/ws/app/data:/app/data:rw
    restart: unless-stopped
