# Conduit - Traefik Reverse Proxy Labels
version: '3'

services:
    homeserver:
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"  # Change this to the name of your Traefik docker proxy network

            - "traefik.http.routers.to-conduit.rule=Host(`<SUBDOMAIN>.<DOMAIN>`)"  # Change to the address on which Conduit is hosted
            - "traefik.http.routers.to-conduit.tls=true"
            - "traefik.http.routers.to-conduit.tls.certresolver=letsencrypt"

    ### Uncomment this if you uncommented Element-Web App in the docker-compose.yml
    # element-web:
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.docker.network=proxy"  # Change this to the name of your Traefik docker proxy network

    #         - "traefik.http.routers.to-element-web.rule=Host(`<SUBDOMAIN>.<DOMAIN>`)"  # Change to the address on which Element-Web is hosted
    #         - "traefik.http.routers.to-element-web.tls=true"
    #         - "traefik.http.routers.to-element-web.tls.certresolver=letsencrypt"
