version: '3'
services:
  actual-ws:
    image: ghcr.io/edgebox-iot/apps/actual:1.0.0
    build:  
      context: "./"
    # ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      # - '5006:5006'
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-actual-ws'
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      VIRTUAL_PORT: 5006
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_NORDIGEN_SECRET_ID=xxxx
      # - ACTUAL_NORDIGEN_SECRET_KEY=xxxx
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    volumes:
      - ./appdata/ws/data:/data