version: "3"
services:
  ##############
  # Pocketbase EdgeApp
  ##############
  pocketbase-ws:
    image: ghcr.io/edgebox-iot/apps/pocketbase:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-pocketbase-ws'
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}


