version: "3"
services:
  ##############
  # NextCloud EdgeApp
  ##############
  nextcloud-ws:
    image: nextcloud:latest
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-nextcloud-ws'
    links:
      - nextcloud-db
    restart: unless-stopped
    volumes:
      # - nextcloud:/var/www/html
      - /media/backupdisk/nextcloud_volume_backup/html:/var/www/html
      - ${NEXTCLOUD_CONFIG-./appdata/config}:/var/www/html/config
      - ${NEXTCLOUD_CUSTOM_APPS_DIR-./appdata/custom_apps}:/var/www/html/custom_apps
      - ${NEXTCLOUD_APPDATA_DIR-../../../data/appdata/nextcloud/}:/var/www/html/data
      - ${NEXTCLOUD_THEMES_DIR-./appdata/themes}:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: nextcloud.edgebox.local${INTERNET_URL}

  nextcloud-db:
    build:
      context: "./bin/nextcloud-db/${BUILD_ARCH}"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-nextcloud-db'
    restart: unless-stopped
    ports:
      - "${HOST_MACHINE_MYSQL_PORT-3307}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-../../ws/appdata/nextcloud/db/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-../../ws/appdata/nextcloud/db/log/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-tiger}
      MYSQL_DATABASE: ${MYSQL_DATABASE-docker}
      MYSQL_USER: ${MYSQL_USER-docker}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-docker}
volumes:
  nextcloud:
