version: "3"

services:
  ##############
  # NextCloud EdgeApp
  ##############
  nextcloud-ws:
    image: ghcr.io/edgebox-iot/apps/nextcloud:1.0.0
    build:
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-nextcloud-ws'
    depends_on:
      nextcloud-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./appdata/nextcloud-ws/var/www/html:/var/www/html:rw
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}

  nextcloud-db:
    image: mariadb:10.3
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-nextcloud-db'
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./appdata/nextcloud-db/var/lib/mysql:/var/lib/mysql:rw
      - ./appdata/nextcloud-db/var/log/mysql:/var/log/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-tiger}
      MYSQL_DATABASE: ${MYSQL_DATABASE-docker}
      MYSQL_USER: ${MYSQL_USER-docker}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-docker}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
