version: "3"
services:
  ##############
  # Home Assistant EdgeApp
  ##############
  home-assistant-ws:
    image: ghcr.io/edgebox-iot/apps/home-assistant:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-home-assistant-ws'
    # network_mode: host
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      VIRTUAL_PORT: 8123
    volumes:
      - ./appdata/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped