version: "3"
services:
  ##############
  # Jupyter EdgeApp
  ##############
  jupyter-ws:
    image: quay.io/jupyter/base-notebook:2026-08-17
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-jupyter-ws'
    user: root
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      VIRTUAL_PORT: 8888
      JUPYTER_TOKEN: ${JUPYTER_TOKEN-}
      JUPYTER_ENABLE_LAB: "yes"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      NB_USER: jovyan
    volumes:
      - ./appdata/ws/notebooks:/home/jovyan/work:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    