
# Base image to base the app container on
FROM collabora/code:latest@sha256:1efda3043e8b9cb437d1b6c6efe20cc3753760e634de012b8dac391da488bf97
LABEL org.opencontainers.image.description Collabora Office is a powerful office suite that supports all major document, spreadsheet and presentation file formats.

# Port to expose from the container into the host
EXPOSE 9980