
# Base image to base the app container on
FROM collabora/code
LABEL org.opencontainers.image.description Collabora Office is a powerful office suite that supports all major document, spreadsheet and presentation file formats.

# Port to expose from the container into the host
EXPOSE 9980