version: "3"
services:
  ##############
  # Calibre Web EdgeApp
  ##############
  calibre-ws:
    image: ghcr.io/linuxserver/calibre-web
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-calibre-ws'
    environment:
      VIRTUAL_HOST: calibre.edgebox.local${INTERNET_URL}
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DOCKER_MODS: linuxserver/calibre-web:calibre
    volumes:
      - ./appdata/config:/config
      - ./appdata/library:/books
    restart: unless-stopped