version: "3"
services:
  ##############
  # Calibre Web EdgeApp
  ##############
  calibre-ws:
    image: ghcr.io/edgebox-iot/apps/calibre:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-calibre-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DOCKER_MODS: linuxserver/calibre-web:calibre
    ports:
      - "8083:8083"
    volumes:
      - ./appdata/config:/config
      - ./appdata/library:/books
    restart: unless-stopped
