version: "3"
services:
  ##############
  # WordPress EdgeApp
  ##############
  wordpress-ws:
    image: ghcr.io/edgebox-iot/apps/wordpress:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-wordpress-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      # VIRTUAL_PROTO: https
      # HTTPS_METHOD: noredirect
      # HTTPS_METHOD: nohttps
    volumes:
      - ./appdata/wordpress-ws:/var/www/html:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - wordpress-db

  wordpress-db:
    image: mysql:8.0
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-wordpress-db'
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: always
    volumes:
      - ./appdata/wordpress-db:/var/lib/mysql:rw