version: "3"
services:
  ##############
  # Jellyfin EdgeApp
  ##############
  jellyfin-ws:
    image: ghcr.io/edgebox-iot/apps/jellyfin:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-jellyfin-ws'
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      VIRTUAL_PORT: 8096
      PUID: 1000
      PGID: 1000
      TZ: ${JELLYFIN_TIMEZONE-Etc/UTC}
      # JELLYFIN_PublishedServerUrl: 192.168.0.5 #optional
    volumes:
      - ./appdata/ws/config:/config
      - ./appdata/ws/data:/data
    # ports:
      # - 8096:8096 (Handled automatically by proxy)
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
