version: "3"
services:
  ##############
  # Traggo EdgeApp
  ##############
  traggo-ws:
    image: ghcr.io/edgebox-iot/apps/traggo:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-traggo-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      VIRTUAL_PORT: 3030
      TRAGGO_DEFAULT_USER_NAME: "${TRAGGO_DEFAULT_USER_NAME-admin}"
      TRAGGO_DEFAULT_USER_PASS: "${TRAGGO_DEFAULT_USER_PASS-traggo}"
    volumes:
      - ./appdata/:/opt/traggo/data:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped