version: "3"
services:
  chatpad-ws:
    image: ghcr.io/edgebox-iot/apps/chatpad:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-chatpad-ws'
    environment:
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}