
# Base image to base the app container on
FROM syncthing/syncthing:2.1.3
LABEL org.opencontainers.image.description Continuous File Synchronization.

# Port to expose from the container into the host
EXPOSE 8384