version: "3"
services:
  ##############
  # Syncthing EdgeApp
  ##############
  syncthing-ws:
    image: ghcr.io/edgebox-iot/apps/${COMPOSE_APP_SLUG-syncthing}:${EDGEAPP_VERSION-1.0.0}
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-${COMPOSE_APP_SLUG-syncthing}-ws'
    restart: unless-stopped
    environment:
      # WS Proxy control varialbles - Do not change
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      # Overridable variables (optional)
      VIRTUAL_PORT: 8384
      # VIRTUAL_PROTO: https
      # VIRTUAL_PATH: /
      # VIRTUAL_DEST: /
      PUID: 1000
      PGID: 1000
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts

    volumes:
      # Recommended defaults
      - /etc/localtime:/etc/localtime:ro
      # Host data volume (Modify as needed by the app)
      - ./appdata/${COMPOSE_APP_SLUG-syncthing}-ws:/var/syncthing/:rw

