name: Docker Build and Publish

on:
  push:
    branches:
      - main

env:
    REGISTRY: ghcr.io


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Publish Docker images
        run: |
          for folder in */; do
            if [ -f "$folder/Dockerfile" ]; then
                image_name="${folder%/}"
                echo "Building Docker image for $image_name"
                version=$(grep EDGEAPP_VERSION $folder/edgebox.env | cut -d '=' -f2)
                docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.REGISTRY }}/$GITHUB_REPOSITORY/$image_name:$version --push $folder
            fi
          done
