version: "3"
services:
  ##############
  # Podgrag Web EdgeApp
  ##############
  podgrab-ws:
    image: ghcr.io/edgebox-iot/apps/podgrab:1.0.0
    build:  
      context: "./"
    container_name: '${COMPOSE_PROJECT_NAME-edgebox}-podgrab-ws'
    environment:
      CHECK_FREQUENCY: 30
      PASSWORD: '${PODGRAB_PASSWORD-mypodcasts}'
      VIRTUAL_HOST: ${LOCAL_URL}${INTERNET_URL}
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - ./appdata/config:/config
      - ./appdata/library:/assets
    restart: unless-stopped